apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-pv-nginx-logs
spec:
  storageClassName: {{.Values.pv_nginx_logs.storageClass}}
  capacity:
    storage: {{.Values.pv_nginx_logs.size}}
  accessModes:
    - {{.Values.pv_nginx_logs.accessModes}}
  persistentVolumeReclaimPolicy: {{.Values.pv_nginx_logs.persistentVolumeReclaimPolicy}}
  hostPath:
    path: {{.Values.pv_nginx_logs.hostPath}}