---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: git@github.com:DmitriyKly/vector-role.git
  scm: git
  name: vector-role

- src: git@github.com:DmitriyKly/lighthouse-role.git
  scm: git
  name: lighthouse-role
