apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Version 1</title>
    </head>
    <body>
        <h1 style="color: blue;">Welcome to Version 1!</h1>
    </body>
    </html>
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }