apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-logs
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /PV/logs/
