apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-logs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  volumeName: pv-nginx-logs # Принудительно связываем PVC с PV 

