apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-html
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  volumeName: pv-nginx-html # Принудительно связываем PVC с PV 

